# Extractive Model Configuration
# DeBERTa-v3-base for span extraction using question-answering approach

# Model Configuration

models:
  - deepset/roberta-base-squad2
  

max_length: 512
stride: 128
n_best: 25
max_answer_length: 30

batch_size: 8
eval_batch_size: 8
epochs: 3
learning_rate: 1e-5

spoiler_type: "multi"
save_dir: "./models_task2"
